FROM node:16

RUN apt-get update && apt-get install --no-install-recommends --yes git
RUN apt-get install --yes docker

WORKDIR /app

COPY / /app

# Install all dependencies
RUN npm install --pure-lockfile

CMD ["npm", "run", "dev:server"]